import { json, readJson, clampInt, safeString } from "../lib/http.js";
import { requirePlayer } from "../lib/auth.js";
import { createDocument, getDocument, mutateDocument, patchDocument } from "../lib/firestore.js";
import { enforceRateLimit, randomToken, sha256Hex } from "../lib/security.js";
import { defaultPlayer, charge, maxInventorySlots } from "../lib/player.js";
import { MISSIONS } from "../data/missions.js";

function nowIso(){return new Date().toISOString();}
function arr(v){return Array.isArray(v)?v:[];}
function obj(v){return v&&typeof v==="object"&&!Array.isArray(v)?v:{};}
function manilaDate(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Manila",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());}
function incMission(progress,action,amount=1){const map={login:["d1","sp4"],play:["d2","d5","w1","w4","m1","m4","ev_s1","ev_s2","sp1"]};const next={...obj(progress)};for(const id of map[action]||[])next[id]=Number(next[id]||0)+amount;return next;}
function deterministicRewardPatch(player,reward){const patch={};if(reward.type==="rp")patch.rp=Number(player.rp||0)+Number(reward.amt||reward.amount||0);else if(["diamond","diamonds"].includes(reward.type))patch.diamonds=Number(player.diamonds||0)+Number(reward.amt||reward.amount||0);else if(reward.type==="mileage")patch.mileage=Number(player.mileage||0)+Number(reward.amt||reward.amount||0);else if(reward.type==="hp")patch.hp=Number(player.hp||0)+Number(reward.amt||reward.amount||0);else if(reward.type==="vip")patch.isVIP=true;else if(reward.type==="PassEXP"){const star={level:1,exp:0,isPremium:false,claimedFree:[],claimedPremium:[],...obj(player.starPass)};star.exp=Number(star.exp||0)+Number(reward.amt||reward.amount||0);while(star.exp>=star.level*100){star.exp-=star.level*100;star.level++;}patch.starPass=star;}else throw Object.assign(new Error("This reward uses a chance-based card grant and stays in compatibility mode"),{status:409,code:"CHANCE_FEATURE_COMPAT_ONLY"});return patch;}

async function currentState(env,uid){return(await getDocument(env,"users",uid)).data;}
async function syncLeaderboard(env,uid,player){const payload={authUid:uid,handle:String(player.handle||"PLAYER"),leagueScore:Math.max(0,Number(player.leagueScore||0)),level:Math.max(1,Number(player.level||1)),profilePic:String(player?.profile?.profilePic||""),updatedAt:nowIso()};const existing=await getDocument(env,"leaderboard",uid,{allowMissing:true});if(!existing)await createDocument(env,"leaderboard",uid,payload);else await patchDocument(env,"leaderboard",uid,payload,existing.updateTime);}
async function guard(request,env,uid,path){const supplied=safeString(request.headers.get("x-request-id")||"",120),id=supplied||crypto.randomUUID();const prior=await env.CATALOG_DB.prepare("SELECT id FROM secure_action_log WHERE id=? AND firebase_uid=?").bind(id,uid).first();return{id,duplicate:!!prior,path};}
async function logAction(env,g,uid,body){const hash=await sha256Hex(JSON.stringify(body||{}));await env.CATALOG_DB.prepare("INSERT OR IGNORE INTO secure_action_log(id,firebase_uid,action,request_hash,status) VALUES(?,?,?,?, 'ok')").bind(g.id,uid,g.path,hash).run();}

async function bootstrapPlayer(request,env,auth){const body=await readJson(request),handle=safeString(body.handle||"",48);if(!handle)throw Object.assign(new Error("Handle is required"),{status:400});const existing=await getDocument(env,"users",auth.uid,{allowMissing:true});if(!existing)await createDocument(env,"users",auth.uid,defaultPlayer(handle,auth.uid));else await mutateDocument(env,"users",auth.uid,async p=>{const patch={authUid:auth.uid,authVersion:3,serverRevision:Number(p.serverRevision||0)+1};if(!p.handle){patch.handle=handle;patch.handleKey=handle.normalize("NFKC").trim().toLowerCase();}const today=manilaDate();if(p.lastMissionLoginDate!==today){patch.lastMissionLoginDate=today;patch.missionProgress=incMission(p.missionProgress,"login",1);}return{patch};});const player=await currentState(env,auth.uid);await syncLeaderboard(env,auth.uid,player).catch(()=>{});return json({ok:true,player});}

async function wallpaper(request,env,auth){const body=await readJson(request),id=safeString(body.id,120);const row=await env.CATALOG_DB.prepare("SELECT id,cost,currency FROM wallpapers WHERE id=?").bind(id).first();if(!row)throw Object.assign(new Error("Wallpaper not found"),{status:404});return mutateDocument(env,"users",auth.uid,async p=>{const owned=arr(p.wallpapers);if(owned.includes(id))throw Object.assign(new Error("Wallpaper already owned"),{status:409});const c=charge(p,String(row.currency||"rp"),Number(row.cost||0));return{patch:{[c.field]:c.next,wallpapers:[...owned,id],serverRevision:Number(p.serverRevision||0)+1},result:{id,cost:Number(row.cost||0),currency:c.field}};});}
async function profilePurchase(request,env,auth){const body=await readJson(request),pfpId=safeString(body.pfpId,160);if(!pfpId)throw Object.assign(new Error("Profile id required"),{status:400});return mutateDocument(env,"users",auth.uid,async p=>{const owned=arr(p.unlockedPFPs);if(owned.includes(pfpId))throw Object.assign(new Error("Profile already owned"),{status:409});const c=charge(p,"rp",20000);return{patch:{rp:c.next,unlockedPFPs:[...owned,pfpId],serverRevision:Number(p.serverRevision||0)+1},result:{pfpId,cost:20000}};});}
async function slots(env,auth){return mutateDocument(env,"users",auth.uid,async p=>{const c=charge(p,"diamonds",50);const bought=Number(p.boughtSlots||0)+50;return{patch:{diamonds:c.next,boughtSlots:bought,serverRevision:Number(p.serverRevision||0)+1},result:{added:50,max:maxInventorySlots({...p,boughtSlots:bought})}};});}
async function exchange(env,auth){return mutateDocument(env,"users",auth.uid,async p=>{const c=charge(p,"rp",1000);return{patch:{rp:c.next,hp:Number(p.hp||0)+5,serverRevision:Number(p.serverRevision||0)+1},result:{spentRP:1000,addedHP:5}};});}
async function coupon(request,env,auth){const body=await readJson(request),code=safeString(body.code,64).toUpperCase();if(!code)throw Object.assign(new Error("Coupon code required"),{status:400});const coupon=await getDocument(env,"coupons",code,{allowMissing:true});if(!coupon)throw Object.assign(new Error("Invalid or expired coupon"),{status:404});return mutateDocument(env,"users",auth.uid,async p=>{const claimed=arr(p.claimedCoupons);if(claimed.includes(code))throw Object.assign(new Error("Coupon already claimed"),{status:409});const data=coupon.data||{};if(data.active===false)throw Object.assign(new Error("Coupon inactive"),{status:410});if(data.expiresAt&&Date.parse(data.expiresAt)<Date.now())throw Object.assign(new Error("Coupon expired"),{status:410});const rewards=Array.isArray(data.rewards)?data.rewards:[data];let shadow={...p},patch={};for(const r of rewards){const rp=deterministicRewardPatch({...shadow,...patch},{type:r.type,amt:Number(r.amount||r.amt||1)});Object.assign(patch,rp);}patch.claimedCoupons=[...claimed,code];patch.serverRevision=Number(p.serverRevision||0)+1;return{patch,result:{code,rewardCount:rewards.length}};});}
async function claimMission(request,env,auth){const body=await readJson(request),id=safeString(body.id,32),mission=MISSIONS[id];if(!mission)throw Object.assign(new Error("Unknown mission"),{status:400});return mutateDocument(env,"users",auth.uid,async p=>{const progress=obj(p.missionProgress),claimed=obj(p.missionClaimed);if(claimed[id])throw Object.assign(new Error("Mission already claimed"),{status:409});if(Number(progress[id]||0)<mission.target)throw Object.assign(new Error("Mission not complete"),{status:409});const rewardPatch=deterministicRewardPatch(p,mission.reward);return{patch:{...rewardPatch,missionClaimed:{...claimed,[id]:true},serverRevision:Number(p.serverRevision||0)+1},result:{id,reward:mission.reward}};});}
async function starPassPurchase(env,auth){return mutateDocument(env,"users",auth.uid,async p=>{const star={level:1,exp:0,isPremium:false,claimedFree:[],claimedPremium:[],...obj(p.starPass)};if(star.isPremium)throw Object.assign(new Error("Premium pass already owned"),{status:409});const c=charge(p,"diamonds",300);star.isPremium=true;return{patch:{diamonds:c.next,starPass:star,serverRevision:Number(p.serverRevision||0)+1},result:{premium:true}};});}
async function starPassClaim(request,env,auth){const body=await readJson(request),level=clampInt(body.level,1,30,1),track=body.track==="premium"?"premium":"free";return mutateDocument(env,"users",auth.uid,async p=>{const star={level:1,exp:0,isPremium:false,claimedFree:[],claimedPremium:[],...obj(p.starPass)};if(star.level<level)throw Object.assign(new Error("Pass tier locked"),{status:409});if(track==="premium"&&!star.isPremium)throw Object.assign(new Error("Premium pass required"),{status:409});const list=track==="premium"?arr(star.claimedPremium):arr(star.claimedFree);if(list.includes(level))throw Object.assign(new Error("Tier already claimed"),{status:409});const milestone=level%5===0;if(track==="premium"&&milestone)throw Object.assign(new Error("Chance-based card tier remains compatibility-only"),{status:409,code:"CHANCE_FEATURE_COMPAT_ONLY"});const reward=track==="free"?(milestone?{type:"diamonds",amt:50}:{type:"rp",amt:5000}):{type:"diamonds",amt:20};const patch=deterministicRewardPatch(p,reward);if(track==="premium")star.claimedPremium=[...list,level];else star.claimedFree=[...list,level];patch.starPass=star;patch.serverRevision=Number(p.serverRevision||0)+1;return{patch,result:{level,track,reward}};});}
async function eventMilestone(request,env,auth){const body=await readJson(request),count=clampInt(body.count,10,100,10);if(count!==10)throw Object.assign(new Error("Card-pack event rewards remain compatibility-only"),{status:409,code:"CHANCE_FEATURE_COMPAT_ONLY"});return mutateDocument(env,"users",auth.uid,async p=>{const claims=obj(p.eventClaims);if(claims[count])throw Object.assign(new Error("Milestone already claimed"),{status:409});if(arr(p.inventory).filter(c=>c?.type!=="material").length<count)throw Object.assign(new Error("Milestone not reached"),{status:409});return{patch:{diamonds:Number(p.diamonds||0)+50,eventClaims:{...claims,[count]:true},serverRevision:Number(p.serverRevision||0)+1},result:{count,reward:{type:"diamonds",amount:50}}};});}
async function shopItem(request,env,auth){const body=await readJson(request),item=safeString(body.item,32);if(item!=="VIP_PASS")throw Object.assign(new Error("This item remains compatibility-only"),{status:409,code:"CHANCE_FEATURE_COMPAT_ONLY"});return mutateDocument(env,"users",auth.uid,async p=>{if(p.isVIP)throw Object.assign(new Error("VIP already active"),{status:409});const c=charge(p,"mileage",100);return{patch:{mileage:c.next,isVIP:true,serverRevision:Number(p.serverRevision||0)+1},result:{item,cost:100}};});}
async function inboxClaim(request,env,auth){const body=await readJson(request),mailId=safeString(body.mailId,180);return mutateDocument(env,"users",auth.uid,async p=>{const inbox=arr(p.inbox).map(m=>structuredClone(m)),i=inbox.findIndex(m=>String(m?.id)===mailId);if(i<0)throw Object.assign(new Error("Mail not found"),{status:404});const mail=inbox[i],patch={};if(mail.type==="pack"||mail.type==="random_card")throw Object.assign(new Error("Chance-based mail remains compatibility-only"),{status:409,code:"CHANCE_FEATURE_COMPAT_ONLY"});if(mail.type==="overflow_cards"){const inventory=arr(p.inventory).slice(),cards=arr(mail.cards),room=Math.max(0,maxInventorySlots(p)-inventory.filter(c=>c?.type!=="material").length),take=cards.slice(0,room),left=cards.slice(room);inventory.push(...take);patch.inventory=inventory;if(left.length){inbox[i]={...mail,cards:left,amount:left.length};}else inbox.splice(i,1);patch.inbox=inbox;return{patch:{...patch,serverRevision:Number(p.serverRevision||0)+1},result:{claimed:take.length,left:left.length}};}Object.assign(patch,deterministicRewardPatch(p,{type:mail.type,amt:Number(mail.amount||1)}));inbox.splice(i,1);patch.inbox=inbox;patch.serverRevision=Number(p.serverRevision||0)+1;return{patch,result:{mailId,type:mail.type}};});}
async function cardbookThemeClaim(request,env,auth){const body=await readJson(request),group=safeString(body.group,100),theme=safeString(body.theme,140);if(!group||!theme)throw Object.assign(new Error("group and theme required"),{status:400});const g=await env.CATALOG_DB.prepare("SELECT slug,name FROM groups WHERE lower(name)=lower(?) OR slug=?").bind(group,group).first();if(!g)throw Object.assign(new Error("Group not found"),{status:404});const t=await env.CATALOG_DB.prepare("SELECT slug,name FROM themes WHERE group_slug=? AND (lower(name)=lower(?) OR slug=?)").bind(g.slug,theme,theme).first();if(!t)throw Object.assign(new Error("Theme not found"),{status:404});const members=(await env.CATALOG_DB.prepare("SELECT name FROM members WHERE group_slug=?").bind(g.slug).all()).results||[];return mutateDocument(env,"users",auth.uid,async p=>{const claims=obj(p.cardBookClaims),claimKey=`${g.name}_${t.name}`;if(claims[claimKey])throw Object.assign(new Error("Theme reward already claimed"),{status:409});const inv=arr(p.inventory);const lower=x=>String(x||"").toLowerCase();for(const m of members){const owned=inv.some(c=>lower(c.group)===lower(g.name)&&lower(c.theme)===lower(t.name)&&lower(c.member)===lower(m.name));if(!owned)throw Object.assign(new Error(`Theme incomplete: missing ${m.name}`),{status:409});}return{patch:{diamonds:Number(p.diamonds||0)+50,cardBookClaims:{...claims,[claimKey]:true},serverRevision:Number(p.serverRevision||0)+1},result:{group:g.name,theme:t.name,reward:{type:"diamonds",amount:50}}};});}
async function cardLock(request,env,auth){const body=await readJson(request),index=Number(body.index);return mutateDocument(env,"users",auth.uid,async p=>{const inventory=arr(p.inventory).map(c=>({...c}));if(!Number.isInteger(index)||!inventory[index])throw Object.assign(new Error("Card not found"),{status:404});inventory[index].locked=body.locked===undefined?!inventory[index].locked:Boolean(body.locked);return{patch:{inventory,serverRevision:Number(p.serverRevision||0)+1},result:{index,locked:inventory[index].locked}};});}
async function sellCard(request,env,auth){const body=await readJson(request),index=Number(body.index);return mutateDocument(env,"users",auth.uid,async p=>{const inventory=arr(p.inventory).map(c=>({...c}));if(!Number.isInteger(index)||!inventory[index])throw Object.assign(new Error("Card not found"),{status:404});const card=inventory[index];if(card.locked)throw Object.assign(new Error("Locked cards cannot be sold"),{status:409});const deck=obj(p.deck);for(const group of Object.values(deck)){if(!group||typeof group!=="object")continue;for(const equipped of Object.values(group)){if(equipped&&equipped.id&&card.id&&equipped.id===card.id)throw Object.assign(new Error("Unequip the card before selling it"),{status:409});}}const saleWeight={R:100,S:50,A:25,B:10,C:5}[String(card.grade||"C").toUpperCase()]||1,rpGain=saleWeight*100;inventory.splice(index,1);return{patch:{inventory,rp:Number(p.rp||0)+rpGain,serverRevision:Number(p.serverRevision||0)+1},result:{rpGain,card}};});}
async function deckAction(request,env,auth){const body=await readJson(request),action=safeString(body.action,16);return mutateDocument(env,"users",auth.uid,async p=>{const inventory=arr(p.inventory),deck=structuredClone(obj(p.deck));if(action==="equip"){const index=Number(body.index),card=inventory[index];if(!Number.isInteger(index)||!card)throw Object.assign(new Error("Card not found"),{status:404});const group=String(card.group||"UNKNOWN"),member=String(card.member||"UNKNOWN");if(!deck[group])deck[group]={};deck[group][member]=card;}else if(action==="unequip"){const group=safeString(body.group,100),member=safeString(body.member,100);if(deck[group])delete deck[group][member];}else if(action==="auto"){const group=safeString(body.group,100);if(!group)throw Object.assign(new Error("Group required"),{status:400});const candidates=inventory.filter(c=>String(c?.group||"").toLowerCase()===group.toLowerCase()&&c.type!=="material"),byMember={},weight={R:5,S:4,A:3,B:2,C:1};for(const card of candidates){const key=String(card.member||"UNKNOWN"),score=(weight[String(card.grade||"C").toUpperCase()]||0)*1000+Number(card.level||1),prev=byMember[key],prevScore=prev?((weight[String(prev.grade||"C").toUpperCase()]||0)*1000+Number(prev.level||1)):-1;if(score>prevScore)byMember[key]=card;}deck[group]=byMember;}else throw Object.assign(new Error("Unknown deck action"),{status:400});return{patch:{deck,serverRevision:Number(p.serverRevision||0)+1},result:{action,deck}};});}
function stageScoreFromServer(player,group,difficulty){const deck=obj(player.deck)[group]||{};let raw=0;const themes=[];const gradeBase={R:101,S:82,A:64,B:46,C:28};for(const card of Object.values(deck)){if(!card)continue;raw+=Math.floor((gradeBase[String(card.grade||"C").toUpperCase()]||10)+Number(card.level||1)*2.5);themes.push(String(card.theme||""));}const counts={};for(const t of themes)counts[t]=(counts[t]||0)+1;const max=themes.length?Math.max(...Object.values(counts)):0;const themeMult=max>=2?1+max*.1:1;const diff=String(difficulty||"EASY").toUpperCase(),diffMult=diff==="HARD"?3:diff==="NORMAL"?2:1;const finalScore=Math.floor((10000*diffMult+(raw*500*diffMult))*themeMult);return{finalScore,earnedRP:Math.floor((finalScore/2000)*diffMult),earnedEXP:50*diffMult,deckRawScore:raw,themeMultiplier:themeMult,diffMult};}
async function startStage(request,env,auth){const body=await readJson(request),token=randomToken(24),now=Date.now(),expires=now+15*60*1000;const meta=JSON.stringify({songId:safeString(body.songId,100),group:safeString(body.group,100)});await env.CATALOG_DB.prepare("INSERT INTO stage_sessions(token,firebase_uid,song_id,difficulty,started_at,expires_at) VALUES(?,?,?,?,?,?)").bind(token,auth.uid,meta,safeString(body.difficulty,32),now,expires).run();return{token,expiresAt:expires};}
async function completeStage(request,env,auth){const body=await readJson(request),token=safeString(body.token,120),row=await env.CATALOG_DB.prepare("SELECT * FROM stage_sessions WHERE token=? AND firebase_uid=?").bind(token,auth.uid).first();if(!row)throw Object.assign(new Error("Stage session not found"),{status:404});const now=Date.now();if(row.completed_at)throw Object.assign(new Error("Stage already submitted"),{status:409});if(now>Number(row.expires_at))throw Object.assign(new Error("Stage session expired"),{status:410});if(now-Number(row.started_at)<10000)throw Object.assign(new Error("Stage completed too quickly"),{status:409});let meta={songId:"",group:""};try{meta=JSON.parse(row.song_id||"{}");}catch{meta.songId=String(row.song_id||"");}await env.CATALOG_DB.prepare("UPDATE stage_sessions SET completed_at=? WHERE token=?").bind(now,token).run();return mutateDocument(env,"users",auth.uid,async p=>{const score=stageScoreFromServer(p,meta.group,row.difficulty);return{patch:{rp:Number(p.rp||0)+score.earnedRP,exp:Number(p.exp||0)+score.earnedEXP,leagueScore:Number(p.leagueScore||0)+score.finalScore,missionProgress:incMission(p.missionProgress,"play",1),serverRevision:Number(p.serverRevision||0)+1},result:{songId:meta.songId,group:meta.group,difficulty:row.difficulty,...score}};});}
async function publicSync(env,auth){const player=await currentState(env,auth.uid);await syncLeaderboard(env,auth.uid,player);return{data:player,result:{synced:true}};}
function resultResponse(out){return json({ok:true,player:out.data,result:out.result});}

export async function playerRoute(request,env,path){if(!path.startsWith("/api/player/"))return null;const auth=await requirePlayer(request,env);await enforceRateLimit(env,auth.uid,"player",120,60);if(path==="/api/player/state"&&request.method==="GET")return json({ok:true,player:await currentState(env,auth.uid)});if(request.method!=="POST")return json({ok:false,error:"Method not allowed"},405);if(path==="/api/player/bootstrap")return bootstrapPlayer(request,env,auth);const g=await guard(request,env,auth.uid,path);if(g.duplicate)return json({ok:true,duplicate:true,player:await currentState(env,auth.uid)});let bodyForLog={};try{bodyForLog=await request.clone().json();}catch{}let out;
 if(path==="/api/player/wallpaper")out=await wallpaper(request,env,auth);else if(path==="/api/player/shop-item")out=await shopItem(request,env,auth);else if(path==="/api/player/profile-purchase")out=await profilePurchase(request,env,auth);else if(path==="/api/player/inventory-slots")out=await slots(env,auth);else if(path==="/api/player/exchange-rp")out=await exchange(env,auth);else if(path==="/api/player/coupon")out=await coupon(request,env,auth);else if(path==="/api/player/mission/claim")out=await claimMission(request,env,auth);else if(path==="/api/player/star-pass/purchase")out=await starPassPurchase(env,auth);else if(path==="/api/player/star-pass/claim")out=await starPassClaim(request,env,auth);else if(path==="/api/player/event/claim")out=await eventMilestone(request,env,auth);else if(path==="/api/player/inbox/claim")out=await inboxClaim(request,env,auth);else if(path==="/api/player/cardbook/theme-claim")out=await cardbookThemeClaim(request,env,auth);else if(path==="/api/player/card/lock")out=await cardLock(request,env,auth);else if(path==="/api/player/card/sell")out=await sellCard(request,env,auth);else if(path==="/api/player/deck")out=await deckAction(request,env,auth);else if(path==="/api/player/public-sync")out=await publicSync(env,auth);else if(path==="/api/player/stage/start")return json({ok:true,...await startStage(request,env,auth)});else if(path==="/api/player/stage/complete")out=await completeStage(request,env,auth);else return json({ok:false,error:"Unknown or compatibility-only player action"},404);
 await logAction(env,g,auth.uid,bodyForLog);if(out?.data)await syncLeaderboard(env,auth.uid,out.data).catch(()=>{});return resultResponse(out);}
