import { ZipReader, BlobReader, BlobWriter } from "@zip.js/zip.js";

const BASES=["https://cdn.jsdelivr.net/gh/kesharrpm/shining-superstar@main/dev/2.0.0/","https://raw.githubusercontent.com/kesharrpm/shining-superstar/main/dev/2.0.0/","https://kesharrpm.github.io/shining-superstar/dev/2.0.0/"];
const j=(x,s=200,h={})=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json; charset=utf-8",...h}});
const t=(x,s=200)=>new Response(x,{status:s});
const cors=r=>{const o=new Response(r.body,r);o.headers.set("access-control-allow-origin","*");o.headers.set("access-control-allow-methods","GET,POST,OPTIONS");o.headers.set("access-control-allow-headers","authorization,content-type,x-bundle-key,x-bundle-kind,x-group,x-theme");return o};
const slug=v=>String(v??"").trim().toLowerCase().replace(/[’']/g,"").replace(/&/g,"and").replace(/\s+/g,"_").replace(/[^a-z0-9_.-]/g,"").replace(/_+/g,"_").replace(/^_+|_+$/g,"");
const norm=v=>String(v||"").replace(/\\/g,"/").replace(/^\/+/,"").replace(/^images\//i,"").replace(/\.(png|webp|jpe?g|gif|avif)$/i,"").toLowerCase();
const pool=v=>v==="true"?true:v==="false"?false:v;

export default{async fetch(req,env,ctx){try{const u=new URL(req.url),p=u.pathname;if(req.method==="OPTIONS")return cors(new Response(null,{status:204}));if(req.method==="GET"&&p==="/api/bootstrap")return cors(await bootstrap(env));if(req.method==="GET"&&p==="/api/theme-data")return cors(await themes(env));if(req.method==="GET"&&p==="/api/wallpapers")return cors(await wallpapers(env));if(req.method==="GET"&&p.startsWith("/a/")){const a=p.split("/").filter(Boolean);return cors(await asset(req,env,ctx,decodeURIComponent(a.slice(2).join("/"))))}return t("SHINING SUPERSTAR Catalog · D1 + Edge Cache")}catch(e){console.error(e);return cors(j({ok:false,error:e?.message||String(e)},500))}}};

async function version(env){return(await env.CATALOG_DB.prepare("SELECT value FROM meta WHERE key='catalog_version'").first())?.value||"1"}
async function bootstrap(env){const[v,g,c]=await Promise.all([version(env),env.CATALOG_DB.prepare("SELECT slug,name FROM groups ORDER BY display_order,name").all(),env.CATALOG_DB.prepare("SELECT (SELECT COUNT(*) FROM groups) groups_count,(SELECT COUNT(*) FROM themes) themes_count,(SELECT COUNT(*) FROM assets) assets_count,(SELECT COUNT(*) FROM bundles WHERE status IN ('indexed','imported')) bundles_count").first()]);return j({version:v,groups:g.results||[],counts:c||{},assetBase:"/a/",storage:"d1-edge"},200,{"cache-control":"public,max-age=60"})}
async function themes(env){const[g,m,th]=await Promise.all([env.CATALOG_DB.prepare("SELECT slug,name FROM groups ORDER BY display_order,name").all(),env.CATALOG_DB.prepare("SELECT group_slug,name FROM members ORDER BY group_slug,display_order,name").all(),env.CATALOG_DB.prepare("SELECT group_slug,name,type,in_pool,limited FROM themes ORDER BY group_slug,display_order,name").all()]),out={},map=new Map;for(const x of g.results||[]){const r={members:[],themes:[],le_themes:[],availability:{}};out[x.name]=r;map.set(x.slug,r)}for(const x of m.results||[])map.get(x.group_slug)?.members.push(x.name);for(const x of th.results||[]){const r=map.get(x.group_slug);if(!r)continue;(x.limited?r.le_themes:r.themes).push(x.name);r.availability[x.name]={type:x.type||"BASIC",in_pool:pool(x.in_pool)}}return j({themeData:out},200,{"cache-control":"public,max-age=300"})}
async function wallpapers(env){const r=await env.CATALOG_DB.prepare("SELECT id,group_name,type,name,cost,currency,legacy_url,source_alias,asset_id FROM wallpapers ORDER BY group_name,id").all();return j({wallpapers:r.results||[]},200,{"cache-control":"public,max-age=300"})}

async function alias(env,a){return env.CATALOG_DB.prepare("SELECT z.source_bundle,z.source_entry,z.original_name,z.mime,z.sha256 FROM asset_aliases x JOIN assets z ON z.id=x.asset_id WHERE x.alias=?").bind(norm(a)).first()}
async function find(env,key){let r=await env.CATALOG_DB.prepare("SELECT a.source_bundle,a.source_entry,a.original_name,a.mime,a.sha256 FROM asset_bindings b JOIN assets a ON a.id=b.asset_id WHERE b.binding_key=?").bind(key).first();if(r)return r;const p=String(key).split(":");if(p[0]==="card"&&p.length>=6){const[,g,th,m,gr,sz]=p,pre=sz==="small"?"c_s":"c_l";for(const a of[`${pre}_${th}_${m}_${gr.toLowerCase()}`,`${pre}_${th}_${m}`,`${pre}_${g}_${th}_${m}_${gr.toLowerCase()}`,`${pre}_${g}_${th}_${m}`])if((r=await alias(env,a)))return r}if(p[0]==="profile"&&p.length>=4){const[,,th,m]=p;for(const a of[`p_${th}_${m}`,`profile_${th}_${m}`,`${th}_${m}`])if((r=await alias(env,a)))return r}if(p[0]==="ghost"&&p.length>=5){const[,,th,m,sz]=p,pre=sz==="small"?"c_s":"c_l";for(const a of[`${pre}_${th}_${m}_em`,`c_l_${th}_${m}_em`,`c_s_${th}_${m}_em`])if((r=await alias(env,a)))return r}return null}
async function source(env,key){if(!env.BUNDLE_PASSWORD)throw Error("BUNDLE_PASSWORD secret is not configured");const b=await env.CATALOG_DB.prepare("SELECT source_file,checksum FROM bundles WHERE manifest_key=?").bind(key).first();if(!b?.source_file)return null;const ver=encodeURIComponent(b.checksum||"unversioned"),cache=caches.default,ck=new Request(`https://bundle-cache.shining.invalid/${ver}/${encodeURIComponent(b.source_file)}`),hit=await cache.match(ck);if(hit)return hit.arrayBuffer();let last;for(const base of BASES)try{const r=await fetch(`${base}${encodeURIComponent(b.source_file)}?v=${ver}`,{cf:{cacheTtl:86400,cacheEverything:true}});if(!r.ok)throw Error(`HTTP ${r.status}`);const ab=await r.arrayBuffer();ctxPut(cache,ck,ab);return ab}catch(e){last=e}throw Error(`Bundle fetch failed: ${last?.message||"unknown"}`)}
function ctxPut(cache,ck,ab){return cache.put(ck,new Response(ab,{headers:{"content-type":"application/octet-stream","cache-control":"public,max-age=86400"}}))}
async function extract(env,a){const ab=await source(env,a.source_bundle);if(!ab)return null;const wanted=norm(a.source_entry||a.original_name),z=new ZipReader(new BlobReader(new Blob([ab])),{password:env.BUNDLE_PASSWORD});try{const es=await z.getEntries(),e=es.find(x=>!x.directory&&norm(x.filename)===wanted);return e?await e.getData(new BlobWriter(a.mime||"image/png"),{password:env.BUNDLE_PASSWORD}):null}finally{await z.close()}}
async function asset(req,env,ctx,key){const cache=caches.default,ck=new Request(req.url,{method:"GET"}),hit=await cache.match(ck);if(hit)return hit;const a=await find(env,key);if(!a)return t("Asset not indexed",404);const b=await extract(env,a);if(!b)return t("Asset entry missing",404);const h=new Headers({"content-type":a.mime||"image/png","cache-control":"public,max-age=2592000,immutable","x-shining-storage":"d1+edge-cache"});if(a.sha256)h.set("etag",`\"${a.sha256}\"`);const r=new Response(b,{headers:h});ctx.waitUntil(cache.put(ck,r.clone()));return r}
